export const trucks = [{
    "id": 1,
    "name": "Mack's BBQ Truck",
    "imageOfTruck": "image url/route",
    "cuisineType": "Barbeque",
    "customerRatings": "1234",
    "customerRatingAvg": null,
    "address": "123 Main. Street San Francisco, CA 94901",
    "lat": "0",
    "long": "1",
    "departureTime": "4:30 PM",
    "nex_address": "456 Last Street San Francisco, CA 94901",
    "next_lat": "2",
    "next_long": "3",
    "next_arrivalTime": "11:00 AM",
    "next_departureTime": "6:00 PM"
},
{
    "id": 2,
    "name": "Nick's Korean BBQ",
    "imageOfTruck": "image url/route",
    "cuisineType": "Korean",
    "customerRatings": "1234",
    "customerRatingAvg": null,
    "address": "123 Main. Street San Francisco, CA 94901",
    "lat": "0",
    "long": "1",
    "departureTime": "4:30 PM",
    "nex_address": "456 Last Street San Francisco, CA 94901",
    "next_lat": "2",
    "next_long": "3",
    "next_arrivalTime": "11:00 AM",
    "next_departureTime": "6:00 PM"
},
{
    "id": 3,
    "name": "Jimmy's Crab Shack",
    "imageOfTruck": "image url/route",
    "cuisineType": "Seafood",
    "customerRatings": "1234",
    "customerRatingAvg": null,
    "address": "123 Main. Street San Francisco, CA 94901",
    "lat": "0",
    "long": "1",
    "departureTime": "4:30 PM",
    "nex_address": "456 Last Street San Francisco, CA 94901",
    "next_lat": "2",
    "next_long": "3",
    "next_arrivalTime": "11:00 AM",
    "next_departureTime": "6:00 PM"
}]